# KUC, PGR107, Lec7


## 1. Arithmetic with NumPy Arrays
### 1.1. basics

In [5]:
import numpy as np

In [13]:
arr = np.array( [[1.,[ 2.], 3.], [4., 5., 6.] ],dtype =np.float16)
print(arr.ndim)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

In [14]:
arr = np.array(   [[1., 2., 3.],
                   [4., 5., 6.],
                   [7., 8., 9.]
                   ]    )
print(arr.ndim)

2


In [15]:

print(arr.ndim)

2


In [16]:
print(type(arr.shape))
m,n = arr.shape
print(m,n)

for i in range(m):
    print(arr[i])


# arr[0]
# arr[1]


<class 'tuple'>
3 3
[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [17]:
print(arr[0,1] == arr[0][1])


True


In [18]:
arr[1][2]

np.float64(6.0)

In [19]:
print(arr[0])
print(arr[0][0])


[1. 2. 3.]
1.0


In [20]:
arr_3 = np.array([arr, arr])
print(arr_3.ndim)
print(arr_3.shape)



3
(2, 3, 3)


In [21]:
#
print(np.zeros(10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
print(np.zeros((3,6)))


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
# try it out yourselves
print(np.zeros([3,6]))

print(np.zeros((3,6))==np.zeros([3,6]))

# check link for documentation: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [24]:
arr1 = np.zeros((5,1), dtype=int)
print(arr1.ndim)


2


In [26]:
arr2 = np.zeros(5,dtype=int)
print(arr1.ndim, arr2.ndim)

arr = np.zeros(10, dtype= np.int8)


2 1


In [30]:
arr3 = np.zeros((2, 1))
arr4 = np.zeros((2,))
print(arr3)
print(arr3.ndim)
print(arr4)



[[0.]
 [0.]]
2
[0. 0.]


In [ ]:
#
arr5 = np.zeros_like ((2,1))
print(arr5)
arr6 = np.zeros_like(arr3)
print(arr6)


In [ ]:
t1= tuple(((2,1),(1,2)))
print(len(t1))

[len(a) for a in t1]


In [44]:
# for different functions in Array:
e1 = np.eye(4,4)
print(e1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## 1.2. try out yourself
######## Try out

In [28]:
# recall the timer? use list and ndarray to compute the same arithmetic function,
# then compare the time needed.
import timeit
start = timeit.default_timer() #time stamp for the staring point

# where you want to implement some functions
list1 = [i for i in range(100)]  #[0,1,2,3....99]
list2 = [i+1 for i in range(100)] #[1,2,3,4....100]
list3 = [(i+j) for i,j in zip(list1,list2)] # [1,3,5,7...]
# print(list1, list2, list3)
end=timeit.default_timer()#time stamp for the ending point
print(end-start)

0.00012024999887216836


In [29]:
start = timeit.default_timer()
arr1 = np.arange(100)
arr2 = arr1+1
arr3 = arr2 + arr1
# print(list1, list2, list3)
end=timeit.default_timer()
print(end-start)


0.00014145899331197143


## 1.3 Try out yourself

In [30]:
def print_time(start):
    end=timeit.default_timer()
    print(end-start)
    return (end-start)


In [33]:
arr = np.arange(100)

start = timeit.default_timer()
arr * arr
time_spent1 = print_time(start)


start = timeit.default_timer()
arr - arr
time_spent2 = print_time(start)

print('The time spent on calculating multiplication is about {} times compared to adding operation: ', time_spent1/time_spent2)



5.1583003369159997e-05
2.8292008209973574e-05
The time spent on calculating multiplication is about {} times compared to adding operation:  1.8232358405359086


## 1.4 data type

In [34]:
int_array = np.arange(3)
print(int_array)

calibers = np.array([.22,.23,.24],dtype=np.float16)
print(calibers)


[0 1 2]
[0.22 0.23 0.24]


In [35]:
int_array_new = int_array.astype(calibers.dtype)
print(int_array_new)
print(int_array)


[0. 1. 2.]
[0 1 2]


In [36]:
#
calibers_new = calibers.astype(int_array.dtype)
print(calibers)
print(calibers_new)

[0.22 0.23 0.24]
[0 0 0]


## 1.4 other arithmetic operations

In [ ]:
1 / arr
arr ** 0.5

In [11]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [12]:
arr = np.array([[2., 6., 2.], [1., 1., 1.]])
print(arr2)
print(arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[2. 6. 2.]
 [1. 1. 1.]]


In [13]:
print(arr2 > arr)



[[False False False]
 [ True  True  True]]
