# KUC, PGR107, Lec7.2

In [47]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12


In [51]:
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


## 2.2 'view'

In [52]:
arr_slice = arr[5:8]
arr_slice

array([   12, 12345,    12])

In [55]:

arr_slice[0] = 12345
print(arr_slice)

[12345 12345    12]


In [56]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## 2.3 two-dimensional

In [57]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [58]:
# arr2d[0][2]
arr2d[0, 2]

3

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
print(arr3d.shape)

(2, 2, 3)


In [60]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [63]:
print(arr3d[1, 0])
print(arr3d[1][0])

[7 8 9]
[7 8 9]


In [64]:
x = arr3d[1]
print(x)
print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


### 2.3.1 2-d slicing

In [65]:
print(arr)
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [66]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
print(arr2d)
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [33]:
arr2d[1, :2]

array([4, 5])

In [34]:
arr2d[:2, 2]

array([3, 6])

In [35]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [36]:
arr2d[:2, 1:] = 0
arr2d


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 2.3.2 try out yourself

In [43]:
arr = np.array([[1, 0, 0],
[4, 0, 0],
[7, 8, 9]])
print(arr.shape)

(3, 3)


In [53]:
arr[2].shape
print(arr[2,:])
print(arr[2:,:].shape)

[7 8 9]
(1, 3)


## 2.4 Boolean Indexing

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.88906855  0.42511765 -0.2167019  -0.14990965]
 [-1.30320891  1.39086742 -1.95097596  0.92478642]
 [-0.31076861  1.78628855 -0.00560437 -1.09180546]
 [ 0.3098047   0.93118554  0.18625879  0.5426174 ]
 [-0.08786568  0.8571408  -0.91821299  0.37315465]
 [ 1.35890464  0.60670686 -0.34671996  0.64161088]
 [ 1.26240828  0.74089465  0.99787999 -1.72741006]]


In [70]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [71]:
data[names == 'Bob']

array([[ 0.88906855,  0.42511765, -0.2167019 , -0.14990965],
       [ 0.3098047 ,  0.93118554,  0.18625879,  0.5426174 ]])

In [58]:
print(data[names == 'Bob', 2:])
# data[names == 'Bob', 3]

[[-0.43670183  0.61926796]
 [ 0.45100106  1.27928438]]


In [59]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 0.77134154, -0.6689614 , -0.7928281 , -0.70045122],
       [ 0.62966362, -0.02701028,  0.10702016, -0.28455877],
       [-0.76866134,  0.39503586,  1.09501753,  0.13217849],
       [ 1.47289043,  0.77806889, -0.30034938,  0.15502661],
       [-0.77865714,  0.81174698, -0.10668945, -0.75979303]])

In [60]:
cond = names == 'Bob'
print(cond)
data[~cond]

[ True False False  True False False False]


array([[ 0.77134154, -0.6689614 , -0.7928281 , -0.70045122],
       [ 0.62966362, -0.02701028,  0.10702016, -0.28455877],
       [-0.76866134,  0.39503586,  1.09501753,  0.13217849],
       [ 1.47289043,  0.77806889, -0.30034938,  0.15502661],
       [-0.77865714,  0.81174698, -0.10668945, -0.75979303]])

In [61]:
# popular way of giving masks, remember how to use!
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[-1.34483761,  0.21312328, -0.43670183,  0.61926796],
       [ 0.62966362, -0.02701028,  0.10702016, -0.28455877],
       [ 1.1737119 , -0.8918302 ,  0.45100106,  1.27928438],
       [-0.76866134,  0.39503586,  1.09501753,  0.13217849]])

In [62]:
data[data < 0] = 0
data

array([[0.        , 0.21312328, 0.        , 0.61926796],
       [0.77134154, 0.        , 0.        , 0.        ],
       [0.62966362, 0.        , 0.10702016, 0.        ],
       [1.1737119 , 0.        , 0.45100106, 1.27928438],
       [0.        , 0.39503586, 1.09501753, 0.13217849],
       [1.47289043, 0.77806889, 0.        , 0.15502661],
       [0.        , 0.81174698, 0.        , 0.        ]])

In [ ]:
# remember how to apply!
data[names != 'Joe'] = 7
data

## 2.5 Fancy Indexing

In [65]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [66]:
print(arr.ndim)

2


In [67]:
arr[[4]].shape

(1, 4)

In [69]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [68]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [70]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
print(arr[[1, 5, 7, 2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [75]:
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])

[ 4 23 29 10]


In [76]:
# try to understand the followings:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 2.6 Transposing Arrays and Swapping Axes

In [78]:
# 2.6.1
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [79]:
# 2.6.2
arr = np.random.randn(6, 3)
arr

array([[ 0.63697306, -1.18581097,  1.07244514],
       [-1.70139562, -0.23206564,  0.45337018],
       [-0.79725826, -0.32794813,  0.92772081],
       [-0.30644488,  0.3516901 , -2.14876415],
       [ 0.57757876, -0.49211767,  0.15528494],
       [-0.91029178,  0.31132914,  0.96850024]])

In [80]:
np.dot(arr.T, arr)

array([[ 5.1922393 , -0.77444553, -0.9613272 ],
       [-0.77444553,  2.03034366, -2.21176835],
       [-0.9613272 , -2.21176835,  7.7956425 ]])

In [82]:
print(np.matmul(arr.T,arr))

[[ 5.1922393  -0.77444553 -0.9613272 ]
 [-0.77444553  2.03034366 -2.21176835]
 [-0.9613272  -2.21176835  7.7956425 ]]


In [89]:
#2.6.3
arr = np.arange(16).reshape((2, 2, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [90]:
print(arr.ndim,arr.shape)

3 (2, 2, 4)


In [111]:
arr = np.arange(15).reshape(5,3,1)
print(arr)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]]


In [112]:
arr1 = arr.transpose((1,0,2))
print(arr1)


[[[ 0]
  [ 3]
  [ 6]
  [ 9]
  [12]]

 [[ 1]
  [ 4]
  [ 7]
  [10]
  [13]]

 [[ 2]
  [ 5]
  [ 8]
  [11]
  [14]]]
