# KUC, PGR107, Lec8


## 1. Transposing Arrays and Swapping Axes

In [5]:
import numpy as np

# 1.1


In [6]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# 1.2

In [ ]:
arr = np.random.randn(6, 3)
arr

In [8]:
np.dot(arr.T, arr)

array([[7.98361538, 4.08170498, 1.04656028],
       [4.08170498, 3.59492741, 0.57504525],
       [1.04656028, 0.57504525, 2.11483272]])

In [9]:
print(np.matmul(arr.T, arr))

[[7.98361538 4.08170498 1.04656028]
 [4.08170498 3.59492741 0.57504525]
 [1.04656028 0.57504525 2.11483272]]


# 1.3

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print(arr.ndim, arr.shape)



In [12]:

arr = np.arange(15).reshape(5, 3, 1)
print(arr)


[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]]]


In [13]:
arr1 = arr.transpose((1, 0, 2))
print(arr1)


[[[ 0]
  [ 3]
  [ 6]
  [ 9]
  [12]]

 [[ 1]
  [ 4]
  [ 7]
  [10]
  [13]]

 [[ 2]
  [ 5]
  [ 8]
  [11]
  [14]]]
