# KUC, PGR107
# Lec8.1
# examples of universal functions

In [1]:
import numpy as np


# 1. recap

In [2]:
x=np.array([1,2,3,4,5,6])
print(x)

print(type(x))
print(x.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [3]:
# x
print('x is: ',x)

x is:  [1 2 3 4 5 6]


In [4]:
# 2d-x
x_2d = x.reshape( (2,3) )#(2,3)
print('new x is:',x_2d)


new x is: [[1 2 3]
 [4 5 6]]


In [5]:

print(x.shape)

(6,)


In [6]:
x= x.reshape((3,))



ValueError: cannot reshape array of size 6 into shape (3,)

In [7]:
print(x)



[1 2 3 4 5 6]


In [7]:
# newaxis
# 1. initialize x
x = np.array([1,2,3])
print(x)
print(x.ndim,x.shape)

[1 2 3]
1 (3,)


In [8]:


x_1 = x[np.newaxis,:]
print(x_1)
print('adding one more dimension before, then the dimensionality and shape are: ', x_1.ndim, x_1.shape)



[[1 2 3]]
adding one more dimension before, then the dimensionality and shape are:  2 (1, 3)


In [10]:
x = np.array([1,2,3])
print(x)
print(x.ndim,x.shape)

x_2 = x[:,np.newaxis]
print(x_2)
print('adding one more dimension before, then the dimensionality and shape are: ', x_2.ndim, x_2.shape)


[1 2 3]
1 (3,)
[[1]
 [2]
 [3]]
adding one more dimension before, then the dimensionality and shape are:  2 (3, 1)


In [11]:
x = np.array([1,2,3])
x_new = x[:,np.newaxis]
print(x_new)
print(x_new.ndim,x_new.shape)
print(x.ndim,x.shape)


[[1]
 [2]
 [3]]
2 (3, 1)
1 (3,)


# 2. Universal Functions: Fast Element-Wise Array Functions
## 2.1 ufunc: arithmetic
## 2.2 commonly used ufuncs

In [12]:
# 2.1

In [13]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [15]:


# arr as numpy ndarray: [0,....9 999]
# 1 option. iterate each element, and calculate the power of 2
# 2. x * 2
# hint info:

print(arr)
print(np.power(arr,3))


[0 1 2 3 4 5 6 7 8 9]
[  0   1   8  27  64 125 216 343 512 729]


In [16]:
np.power(arr,2)
import timeit
start = timeit.default_timer()








In [17]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [18]:
x = np.random.randn(8)
print(x)
y = np.random.randn(8)
print(y)


[ 0.39056502 -0.1412458  -1.29369402  0.97478259  0.41223836 -0.06394238
 -0.34384577 -0.43094337]
[-1.37069153 -0.51561855  0.16570396  0.11039479 -0.351745    1.24877475
  0.99205462  0.40235093]


In [19]:
np.maximum(x, y)


array([ 0.39056502, -0.1412458 ,  0.16570396,  0.97478259,  0.41223836,
        1.24877475,  0.99205462,  0.40235093])

In [20]:
np.sum

<function sum at 0x109e802f0>

In [21]:
## calculate time being used during the calculation

In [22]:
import timeit
start = timeit.default_timer()
x = np.arange(10)
# print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("x mod 2 =", x % 2)
print(timeit.default_timer()-start)

x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 2 = [ 0  2  4  6  8 10 12 14 16 18]
x / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x // 2 = [0 0 1 1 2 2 3 3 4 4]
x ** 2 = [ 0  1  4  9 16 25 36 49 64 81]
x mod 2 = [0 1 0 1 0 1 0 1 0 1]
0.000596166995819658


In [23]:
# 2.2
arr = np.random.randn(4, 4)
print(arr)

[[-0.72379027  0.96035208 -0.2943743  -0.02396343]
 [ 1.10480312 -0.98845731 -1.05269682 -1.44411376]
 [ 0.61004837 -0.73045468  0.171312   -1.06163938]
 [-0.06085558 -0.01424501 -0.28941269 -0.87107761]]


In [24]:

print(arr > 0)

[[False  True False False]
 [ True False False False]
 [ True False  True False]
 [False False False False]]


In [25]:
print(np.where(arr > 0, 2, -2))

[[-2  2 -2 -2]
 [ 2 -2 -2 -2]
 [ 2 -2  2 -2]
 [-2 -2 -2 -2]]


In [26]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.72379027,  2.        , -0.2943743 , -0.02396343],
       [ 2.        , -0.98845731, -1.05269682, -1.44411376],
       [ 2.        , -0.73045468,  2.        , -1.06163938],
       [-0.06085558, -0.01424501, -0.28941269, -0.87107761]])

In [27]:
arr = np.random.randn(2, 2)
print(arr)
arr.mean()
np.mean(arr)
arr.sum()

[[-1.01610528  0.19968999]
 [-0.79584844 -0.15089561]]


np.float64(-1.76315933228397)

In [28]:
arr.mean(axis=1)

array([-0.40820764, -0.47337202])

In [29]:
arr.sum(axis=0)



array([-1.81195372,  0.04879439])

In [30]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values


np.int64(48)

In [31]:
# add a simple example to remind yourself
arr = np.array([[1,2], [3, 4]])
print(arr)
print(arr[0], arr[1])

[[1 2]
 [3 4]]
[1 2] [3 4]


In [32]:
print(arr.sum(axis= 0))

[4 6]


In [33]:
arr.sum(axis= 1)

array([3, 7])