# Python Programming PGR107

# P8

In [ ]:
## P8.1


In [ ]:
import numpy as np

# 3.1.1
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

# 3.1.2
print("A + B:", A + B)
print("A - B:", A - B)
print("A * B:", A * B)
print("A / B:", A / B)

# P8.2

In [4]:
C = np.array([2, 7, 1, 8, 2, 8, 1, 8, 2, 8])

# 3.2.1
print("sum(C):", np.sum(C))

# 3.2.2
print("prod(C):", np.prod(C))

# 3.2.3
print("cumsum(C):", np.cumsum(C))

sum(C): 47
prod(C): 229376
cumsum(C): [ 2  9 10 18 20 28 29 37 39 47]


# P8.3

In [ ]:
# 3.3.1
D = np.array([[1, 2, 3], [4, 5, 6]])
E = np.array([1, 2, 1])
print("D + E:", D + E)
print("")

In [14]:
print(D[1]*15)

[60 75 90]


In [13]:
# 3.3.2
F = np.array([1, 2]).reshape(-1, 1)
print("D + F:\n", D + F)

D + E: [[2 4 4]
 [5 7 7]]

D + F:
 [[2 3 4]
 [6 7 8]]


# P8.4


In [6]:
# 3.4.1
G = np.random.randint(1, 10, (5, 4, 3))
H = np.array([1, 2, 3])
result1 = G - H
print("Result 3.4.1:\n", result1)
print("")

Result 3.4.1:
 [[[ 5 -1 -1]
  [ 0  1  5]
  [ 7  7 -1]
  [ 3  1  0]]

 [[ 7  0  1]
  [ 0  1 -2]
  [ 0  3  4]
  [ 3  2 -1]]

 [[ 8  1  6]
  [ 4  4  3]
  [ 7  7 -1]
  [ 2  0  2]]

 [[ 2  3  2]
  [ 4  7  6]
  [ 3  7  2]
  [ 5  2 -2]]

 [[ 2  3  2]
  [ 6  0  1]
  [ 5  6  0]
  [ 1 -1  4]]]



In [10]:
print(G)

[[[6 1 2]
  [1 3 8]
  [8 9 2]
  [4 3 3]]

 [[8 2 4]
  [1 3 1]
  [1 5 7]
  [4 4 2]]

 [[9 3 9]
  [5 6 6]
  [8 9 2]
  [3 2 5]]

 [[3 5 5]
  [5 9 9]
  [4 9 5]
  [6 4 1]]

 [[3 5 5]
  [7 2 4]
  [6 8 3]
  [2 1 7]]]


In [24]:
I = np.copy(G)
print(I)
print(H)

[[[1 7 8]
  [7 3 4]
  [2 3 6]
  [9 8 1]]

 [[2 9 2]
  [5 7 7]
  [4 9 5]
  [3 3 9]]

 [[3 1 4]
  [7 8 7]
  [3 1 4]
  [1 4 2]]

 [[6 2 4]
  [3 6 4]
  [3 6 7]
  [6 1 1]]

 [[7 7 4]
  [1 8 5]
  [4 4 1]
  [3 9 2]]]
[1 2 3]


In [25]:
print(I*H)

[[[ 1 14 24]
  [ 7  6 12]
  [ 2  6 18]
  [ 9 16  3]]

 [[ 2 18  6]
  [ 5 14 21]
  [ 4 18 15]
  [ 3  6 27]]

 [[ 3  2 12]
  [ 7 16 21]
  [ 3  2 12]
  [ 1  8  6]]

 [[ 6  4 12]
  [ 3 12 12]
  [ 3 12 21]
  [ 6  2  3]]

 [[ 7 14 12]
  [ 1 16 15]
  [ 4  8  3]
  [ 3 18  6]]]


In [18]:
# 3.4.2
I = np.array([[1], [2], [3], [4]])
result2 = G + I
print("Result 3.4.2:\n", result2)

Result 3.4.1:
 [[[ 3  2  1]
  [ 7  2  3]
  [ 0  5  0]
  [ 5  1  2]]

 [[ 5  6  4]
  [ 2  6  4]
  [ 5  7  4]
  [ 8  4 -2]]

 [[ 4  2  6]
  [ 7  7  4]
  [ 5  5  0]
  [ 8  5  4]]

 [[ 6  3  3]
  [ 3  7  1]
  [ 3  4  5]
  [ 8  1 -1]]

 [[ 2  4  4]
  [ 6 -1 -2]
  [ 3  3  4]
  [ 0 -1  5]]]

Result 3.4.2:
 [[[ 5  5  5]
  [10  6  8]
  [ 4 10  6]
  [10  7  9]]

 [[ 7  9  8]
  [ 5 10  9]
  [ 9 12 10]
  [13 10  5]]

 [[ 6  5 10]
  [10 11  9]
  [ 9 10  6]
  [13 11 11]]

 [[ 8  6  7]
  [ 6 11  6]
  [ 7  9 11]
  [13  7  6]]

 [[ 4  7  8]
  [ 9  3  3]
  [ 7  8 10]
  [ 5  5 12]]]
